[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "spark_dataset_interfaces"
version = "0.0.1"
dependencies = [
    "imageio",
    "numpy",
    "pandas",
    "scipy",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.isort]
profile = "black"
